### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by sdfantasy** [pentaho/pentaho-cassandra-plugin#132]
I hava a casandra read transform,but it sometimes is not work. here is the log:

2018-07-05 04:00:04,554 ERROR [org.pentaho.di] 2018/07/05 04:00:04 - 读取站点属性.0 - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : Unexpected error
2018-07-05 04:00:04,562 ERROR [org.pentaho.di] 2018/07/05 04:00:04 - 读取站点属性.0 - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : java.lang.NoClassDefFoundError: io/netty/util/internal/TypeParameterMatcher
2018/07/05 04:00:04 - 读取站点属性.0 - 	at java.lang.Class.forName0(Native Method)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at java.lang.Class.forName(Class.java:344)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at io.netty.util.internal.JavassistTypeParameterMatcherGenerator.generate(JavassistTypeParameterMatcherGenerator.java:62)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at io.netty.util.internal.JavassistTypeParameterMatcherGenerator.generate(JavassistTypeParameterMatcherGenerator.java:54)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at io.netty.util.internal.TypeParameterMatcher.get(TypeParameterMatcher.java:42)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at io.netty.util.internal.TypeParameterMatcher.find(TypeParameterMatcher.java:78)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at io.netty.channel.SimpleChannelInboundHandler.<init>(SimpleChannelInboundHandler.java:67)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at io.netty.channel.SimpleChannelInboundHandler.<init>(SimpleChannelInboundHandler.java:57)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Connection$Dispatcher.<init>(Connection.java:1017)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Connection.<init>(Connection.java:116)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Connection.<init>(Connection.java:128)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Connection$Factory.open(Connection.java:806)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:252)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:201)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1619)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1537)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:399)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at org.pentaho.cassandra.driver.datastax.DriverConnection.getKeyspace(DriverConnection.java:152)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at org.pentaho.di.trans.steps.cassandrainput.CassandraInput.processRow(CassandraInput.java:156)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at java.lang.Thread.run(Thread.java:745)
2018/07/05 04:00:04 - 读取站点属性.0 - Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.TypeParameterMatcher
2018/07/05 04:00:04 - 读取站点属性.0 - 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291)
2018/07/05 04:00:04 - 读取站点属性.0 - 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
2018/07/05 04:00:04 - 读取站点属性.0 - 	... 22 more

**Comment by ihepda** [comment]
Hello all,
I've the same issue. Any idea?

Regards

**Comment by ihepda** [comment]
Hello,
I've resolved putting the netty-common-4.0.44.Final.jar file into lib folder. It seems to be a time problem. If I run pentaho with remote debugging parameters the problem does not appear. 
Regards
