### ISSUE TITLE
java.lang.ClassNotFoundException: org.pentaho.di.ui.trans.steps.cassandrainput.CassandraInputDialog

### ISSUE THREAD

**Issue by owocki** [pentaho/pentaho-cassandra-plugin#46]
I get the following error message when trying to create a `Cassandra Input` step.

<img src='http://bits.owocki.com/image/363A2S2T4644/Screen%20Shot%202014-09-21%20at%207.15.20%20PM.png'/>

Here's the exception:

```
java.lang.ClassNotFoundException: org.pentaho.di.ui.trans.steps.cassandrainput.CassandraInputDialog
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:87)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.getStepDialog(SpoonStepsDelegate.java:231)
	at org.pentaho.di.ui.spoon.Spoon.getStepEntryDialog(Spoon.java:8488)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8648)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3020)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:737)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1297)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7801)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9130)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:638)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at apple.launcher.LaunchRunner.run(LaunchRunner.java:116)
	at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
	at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)
```

I followed the instructions on the README.md file, copied the dist over from the `pentaho-cassandra-plugin` directory after building in with `ant`.

**Comment by matthewtckr** [comment]
We've been unable to reproduce this issue on several different machines while researching [PDI-12507](http://jira.pentaho.com/browse/PDI-12507).  You might try using Java 8 and PDI 6.1 or later, to see if the issue still occurs.  If it does, please create a new issue at http://jira.pentaho.com/secure/Dashboard.jspa.
