### ISSUE TITLE
Cassndra access exceptions

### ISSUE THREAD

**Issue by salahaldin** [pentaho/pentaho-cassandra-plugin#55]
Hello, 
First of all sorry for duplicate the question. http://forums.pentaho.com/showthread.php?195135-Access-to-Cassandra.

I am trying to access cassandra using port 1960; however I get this error.
InvalidRequestException(why:Undefined name column_aliases in selection clause)
at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:49032)
at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result$execute_cql3_query_resultStandardScheme.read(Cassandra.java:49009)
The option Use CQL version 3 is cheked.

If I try to use port 9042 I get the following error
org.apache.thrift.transport.TTransportException: Read a negative frame size (-2080374784)!
at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:133)
at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)

The build version is 5.4.0.1

Thanks in advance

**Comment by dkincade** [comment]
Please use the forum case as the isue tracker in github is not used by Pentaho.
